### ISSUE TITLE
CID conversion error

### ISSUE THREAD

**Issue by icidasset** [fission-suite/webnative#345]
```
  index.js:73 TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at decodeCID (auth.fission.codes/worker.min.js:2989:14)
    at DAGService.get (auth.fission.codes/worker.min.js:3055:64)
```
Problem with https://github.com/icidasset/nourish
Have not seen it in other apps yet.

**Comment by icidasset** [comment]
This was because `fromCID` was used with a CID encoded as a string. Typescript should avoid this issue, but for the people using just javascript, we should probably add a better error message.
